# Generated by Django 4.2.3 on 2023-08-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adviritisments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='creted_at',
            new_name='created_at',
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
